### ISSUE TITLE
KumuluzEE BOM missing openapi

### ISSUE THREAD

**Issue by pr3mar** [kumuluz/kumuluzee#100]
Hello,

I noticed that openapi is missing in the [KumuluzEE BOM](https://github.com/kumuluz/kumuluzee/blob/f095a7f5461a9284904e486923adfc50cde25cd0/bom/pom.xml)

Regards

**Comment by jmezna** [comment]
KumuluzEE BOM includes only the Java EE components, that are provided by the KumuluzEE microservice framework, and implemented MicroProfile specifications. 

KumuluzEE OpenAPI is a standalone project and shall thus bi included directly.
