### ISSUE TITLE
Running uberjar fails sometimes (and same goes for exploded)

### ISSUE THREAD

**Issue by TapaniRundgren** [kumuluz/kumuluzee#103]
Have issues when running kumuluzee -based application.
Same symptoms as in "Running uberjar fails infrequently #87" in closed issues.
Using JPA, REST and OpenAPI.
Maven 3.5.2
Java openjdk version "11-ea" 2018-09-25 (but same behaviour even with Java10 and 8)
Happens in Windows 10 and in Docker with Alpine Linux
Using Kumuluzee 2.5.3.
One thing that I can say about my project is that it has a large number of entitiy classes.
Succeeded to recreate same thing with kumuluz-samples/kumuluz-rest (when i added OpenAPI or Swagger)
[kumuluzee-failures.txt](https://github.com/kumuluz/kumuluzee/files/2123296/kumuluzee-failures.txt)
CTRL-C to terminate between runs

**Comment by TapaniRundgren** [comment]
One more thing:
- seems to always work when started with: mvn kumuluzee:run

**Comment by TapaniRundgren** [comment]
Pushed wrong button ...

**Comment by TapaniRundgren** [comment]
Additional information:
- was executimg the java -jar command in git bash window
using cmd.exe now with exploded config and I can't reproduce the problem

**Comment by cen1** [comment]
Do you specify the `-cp` flag when running exploded? I didn't see it in your txt.

**Comment by TapaniRundgren** [comment]
Yes, I did. When running in git bash window, you need to use one escape character to get it working

**Comment by TapaniRundgren** [comment]
The use of exploded  form makes it more difficult to backed with docker - now I have it working, but would still prefer to use "java -jar application.jar" -format for running in docker too.
For now I package the target with maven-assembly-plugin into a tar -file for deploying into docker container

**Comment by cen1** [comment]
Offtopic: you can also use something like this in Dockerfile:
```
RUN mkdir /app
WORKDIR /app
ADD ./api/target/ /app
CMD ["java", "-server", "-cp", "classes:dependency/*", "com.kumuluz.ee.EeApplication"]
```
