### ISSUE TITLE
Uberjar returns 404 if the JAX-RS resources are in a jar

### ISSUE THREAD

**Issue by andref** [kumuluz/kumuluzee#118]
I have a multimodule maven project organized such that one module is the JAX-RS application and another module is the KumuluzEE app itself. The latter depends on the former. I have pushed a very small repo to demonstrate the issue at https://github.com/andref/kumuluzee-uberjar-bug.

The app runs fine from any IDE or from the command line:

```sh
java -cp $(ls application/target/classes/lib/*.jar | paste -s -d":" -) \
     com.kumuluz.ee.EeApplication
```

During the start-up process, it notes:

```
INFO -- KumuluzEE running in an exploded class and dependency runtime.
```

The app responds as expected:

```sh
$ curl -X HEAD -I http://localhost:8080/v1/hello
HTTP/1.1 200 OK
Date: Sat, 01 Sep 2018 17:21:08 GMT
X-Powered-By: KumuluzEE/2.5.3
Content-Type: application/json
Content-Length: 11
Server: Jetty(9.4.8.v20171121)
```

Now, if I run the uberjar generated by the kumuluzee-maven-plugin, things go wrong. The app notes:

```
INFO -- KumuluzEE running inside a JAR runtime.
```

And although it appears to be running, it does not respond:

```sh
$ curl -X HEAD -I http://localhost:8080/v1/hello
HTTP/1.1 404 Not Found
Date: Sat, 01 Sep 2018 17:21:56 GMT
X-Powered-By: KumuluzEE/2.5.3
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1
Content-Length: 324
Server: Jetty(9.4.8.v20171121)
```

As there's nothing really weird about packaging the JAX-RS resources and application in a jar (since the equivalent war webapp would run just fine), I believe this must be a bug in either the maven plugin or the class loading mechanism used by the uberjar.

**Comment by urbim** [comment]
Hi!

KumuluzEE Uber JAR packaging does not support annotation scanning in project's dependencies. It only scans application classes.

You have some options. We recommend keeping the JAX-RS classes in main application. Or you can run your application as exploded, which supports dependency scanning.

Another option is creating a JAX-RS dynamic feature class in your main application and registering resources from libraries manually.

**Comment by andref** [comment]
@urbim is it just not implemented or is there a fundamental reason why it's not supported? If you point me at the right direction, I might be able to contribute a patch to add support for that.

**Comment by urbim** [comment]
We decided not to support it. If I recall correctly, the main reason was it slowed down our start-up times significantly.

**Comment by andref** [comment]
@urbim of course! that makes sense. Now, I tried using the capsule maven plugin to generate a the uberjar
