### ISSUE TITLE
Great idea, but any plan for including service registry and communication?

### ISSUE THREAD

**Issue by cfcodefans** [kumuluz/kumuluzee#12]
such as zookeeper and queue?

**Comment by TFaga** [comment]
Hello!

Yes, definitely. Right now I am mostly focusing on adding the last remaining Java EE components. After that we will begin to add aditional features such as the ones you mentioned.

To be more specific. At the top of the list is indeed service discovery (either zookeeper or etcd), database migrations (most likely liquibase) and a management/monitoring system.

As for a messaging queue server.  I think that it will be added as an option. The framework, however, is encouraging the microservice pattern with your applications. Which means that it is encouraged to use an external messaging system (hornetmq, rabbitmq, ...), like you would use an external database. This helps towards making your microservice stateless and easily scalable.

That said, MDBs will be added shortly, as well as support for other non JMS clients (such as RabbitMQ with the AMQP protocol).

**Comment by MBJuric** [comment]
We have added support for service discovery: https://github.com/kumuluz/kumuluzee-discovery
You might also want to look at config support: https://github.com/kumuluz/kumuluzee/wiki/Configuration and https://github.com/kumuluz/kumuluzee-config
We have also added event streaming support with Apache Kafka: https://github.com/kumuluz/kumuluzee-streaming
