### ISSUE TITLE
Any plans to implement Microprofile 2.0?

### ISSUE THREAD

**Issue by TapaniRundgren** [kumuluz/kumuluzee#126]
Is the work in progress already?

**Comment by MBJuric** [comment]
Hello,
We are working on the Microprofile 2.0/2.1 compliance. Full Microprofile 2.1 compliance will be available by the end of this year. With KumuluzEE 3.0 we already provide support for the following required APIs: Java SE 8/9/10/11, CDI 2.0, JAX-RS 2.1, JSON-B 1.0, JSON-P 1.1 and CA 1.3.
KumuluzEE 3.0 currently provides support for MicroProfile Config 1.3, Fault Tolerance 1.0, Health Check 1.0, JWT Authentication 1.0, Metrics 1.1, OpenAPI 1.0 and Rest Client 1.0. Support for OpenTracing 1.2 will follow soon (beginning of December). 
Please notice however, that KumuluzEE provides support for many cloud-native functionalities not found in Microprofile, but very useful for true cloud-native microservices, including:
- Service discovery with support for etcd and Consul,
- REST extensions for simple paging, querying and filtering,
- Logging framework for centralized log management,
- Event Streaming extensions for Apache Kafka,
- Reactive extensions for Vert.x,
- gRPC support,
- GraphQL support,
- Ethereum support. 
We also provide support for Node.js (already released) and Go (coming very soon). 
Thanks for your interest and best regards.
