### ISSUE TITLE
Any sample on Mojarra JSF

### ISSUE THREAD

**Issue by alexrm** [kumuluz/kumuluzee#13]
Hi, great framework, specially to Microservices architecture... Nevertheless i would like packaging a JSF based application... any sample on this ?

**Comment by lathspell** [comment]
There is a sample in https://github.com/TFaga/kumuluzee-examples/tree/master/java-magazine-trains/ui

It does not work though, see issue #1 there.

**Comment by osbeorn** [comment]
Take a look at this sample: https://github.com/kumuluz/kumuluzee-samples/tree/master/jsf
