### ISSUE TITLE
Old dependency on jackson-annotation from kumuluzee-microProfile-2.1

### ISSUE THREAD

**Issue by jefrajames** [kumuluz/kumuluzee#139]
It seems that kumuluzee-microProfile-2.1 depends on jackson-annotations 2.8.11 which triggers a ClassNotFoundException on com.fasterxml.jackson.annotation.JSonMerge when starting my application (MicroProfile + GraphQL).
Other parts of KumuluzEE depends on jackson 2.9.X which requires JSonMerge.
I've excluded jackson-annotations dependency from kumuluzee-microProfile-2.1 and my application now starts without any error:
` <dependency>
>           <groupId>com.kumuluz.ee</groupId>
>            <artifactId>kumuluzee-microProfile-2.1</artifactId>
>           <exclusions>
>                
>                <exclusion>
>                    <groupId>com.fasterxml.jackson.core</groupId>
>                    <artifactId>jackson-annotations</artifactId>
>                </exclusion>
>            </exclusions>
>        </dependency>`

**Comment by urbim** [comment]
Hi!

Actually, majority of Kumuluz framework runs on jackson 2.8.11, but we plan to upgrade to 2.9.x in the near future.

Thanks for the report!

**Comment by urbim** [comment]
Fixed in 3.3.0.
