### ISSUE TITLE
Dependencys Problem

### ISSUE THREAD

**Issue by ArtHoffmann** [kumuluz/kumuluzee#144]
Hello, we've discovered a bug in the dependencies. The error occurs when you include Swagger. To fix the problem we had to remove the following dependency:

```
 <exclusion>
                    <groupId>org.glassfish.jersey.containers</groupId>
                    <artifactId>jersey-container-servlet-core</artifactId>
 </exclusion>

```
The problem is caused by the 2 different versions of jersey

![image](https://user-images.githubusercontent.com/24555132/56372601-9708c580-61ff-11e9-9fc8-029c3b9232ba.png)

Thanks!

**Comment by zvonegit** [comment]
Hello @ArtHoffmann,

Can you try with kumuluzee-swagger version [1.2.1](https://github.com/kumuluz/kumuluzee-swagger/releases/tag/v1.2.1)?

**Comment by ArtHoffmann** [comment]
Hello, yes I am using version 1.2.1

` <kumuluzee-swagger.version>1.2.1</kumuluzee-swagger.version>`

**Comment by zvonegit** [comment]
Hi,

Kumuluzee-swagger v1.2.2 was released with the fix for your issue. Please check.
Thank you!

**Comment by ArtHoffmann** [comment]
It works.

Thank you!
