### ISSUE TITLE
no-web server

### ISSUE THREAD

**Issue by ikonkere** [kumuluz/kumuluzee#147]
It's not currently possible to create applications that don't use web/servlets, because the only @Server implementation available is the one with Jetty. Spring-boot, Thorntail and others support running without a servlet container (completely omitting it from the final distribution) and so should Kumuluz. I created my own simple @Server that just initializes `javax.enterprise.inject.se.SeContainer` and it actually works, so it shouldn't be a big deal to do so "officially".

**Comment by MBJuric** [comment]
We will address this in the near future. however, if you can contribute your solution, this would be much appreciated.

**Comment by ikonkere** [comment]
Fair enough, i'll look into it. There's something else though: my enterprise is looking to start actively using KumuluzEE as MP runtime and i've already found some other stuff and/or bugs.

I see there's little activity here, so do you guys hang out on some public collaboration platforms like Zulip or google groups? Our organization can't opt into Kumuluz enterprise support for certain reasons, so i'm looking for more informal collaboration :).

**Comment by MBJuric** [comment]
You are very welcome to use KumuluzEE for production. Our framework has been used by several large companies (including energy, oil&gas, banking, insurance, automotive, etc.). You can submit bug reports here or use our email address. We'll make sure to provide solutions and fixes.

**Comment by ikonkere** [comment]
But no online collaboration options outside paid support, correct?

**Comment by MBJuric** [comment]
Github issues or email. No other online tool. Best regards.

**Comment by ikonkere** [comment]
Move discussion to https://github.com/kumuluz/kumuluzee/pull/150
