### ISSUE TITLE
Getting Started needs command for Windows

### ISSUE THREAD

**Issue by MungTheWicked** [kumuluz/kumuluzee#16]
It would be very helpful for the Getting Started guide to have the following Windows syntax for running jar files specified alongside the Linux/UNIX syntax:

java -classpath "target\classes;target\dependency*" com.kumuluz.ee.EeApplication

I just verified that the command works.

**Comment by blaz1** [comment]
Hello,

the given command did not work for me in Windows (Console2 app). I had to add "\" after "dependency". Corrected version:

java -classpath "target\classes;target\dependency\*" com.kumuluz.ee.EeApplication

**Comment by surajtamang** [comment]
This one works for me in the windows platform.

First open two terminals
Second go to your workspace path: C:\workspace\kumuluzee-example-master>
in both terminals

In first command terminal, give below commands:
set PORT=3000
java -cp catalogue/target/classes;catalogue/target/dependency/* com.kumuluz.ee.EeApplication

In second command terminal, give below commands:
set PORT=3001
java -cp orders/target/classes;orders/target/dependency/* com.kumuluz.ee.EeApplication

Check out the ";" in between two given paths, in *IX system give ":" .

**Comment by MBJuric** [comment]
Please look at the KumuluzEE Samples: https://github.com/kumuluz/kumuluzee-samples
They include Windows commands.
