### ISSUE TITLE
Bom or not ?.

### ISSUE THREAD

**Issue by pierre-gautier** [kumuluz/kumuluzee#161]
Hi,

I'm trying to understand how to import Kumuluzee in maven.

Should I use the artifact kumuluzee-microProfile-3.0 defined in the BOM, or the kumuluzee-microProfile-3.2defined in the parent ?

Thanks !

**Comment by jmezna** [comment]
Use the dependency from the bom, as shown in the [sample](https://github.com/kumuluz/kumuluzee-samples/blob/master/kumuluzee-microProfile-1.2/pom.xml).

**Comment by pierre-gautier** [comment]
Fine, thanks.
Any idea why is the version 3.0 defined in the BOM while the version 3.2 is in the parent ?
