### ISSUE TITLE
Use kumuluz with jrebel

### ISSUE THREAD

**Issue by clpCoder** [kumuluz/kumuluzee#163]
Hi everyone,

I tried using jrebel in netbeans with kumuluz, but I am having difficulty integrating it, I followed the lines on the next page:
https://manuals.jrebel.com/jrebel/standalone/maven.html

I have also tried removing kumuluz jetty server and running it independently and using maven (https://manuals.jrebel.com/jrebel/standalone/launch-from-command-line.html#jettycli) but got no results either.

my last attempt was to use agentpath with jrebel path and main com.kumuluz.ee.EeApplication file location but it doesn't work.

can anybody help me?

**Comment by cen1** [comment]
Hi

I tried JRebel IntelliJ plugin and it works as expected. I opened our kumuluzee-samples project, kumuluzee-rest module. Started the app with JRebel, modified an endpoint, rebuilt module and the endpoint changed accordingly without restarting the framework.

**Comment by clpCoder** [comment]
> Hi
> 
> I tried JRebel IntelliJ plugin and it works as expected. I opened our kumuluzee-samples project, kumuluzee-rest module. Started the app with JRebel, modified an endpoint, rebuilt module and the endpoint changed accordingly without restarting the framework.

can you show me the configuration you made ?, JRebel is activated, but the icon to execute it is deactivated

**Comment by cen1** [comment]
I just followed the docs, nothing particular. Hope this helps in any way.

<img width="351" alt="Screenshot 2020-06-19 at 09 09 06" src="https://user-images.githubusercontent.com/1158861/85106929-5b0b2f00-b20d-11ea-82ac-a73e8466a23b.png">
<img width="740" alt="Screenshot 2020-06-19 at 09 08 09" src="https://user-images.githubusercontent.com/1158861/85106934-5c3c5c00-b20d-11ea-96b8-1004093800fa.png">
"Rebel Run"
<img width="364" alt="Screenshot 2020-06-19 at 09 08 22" src="https://user-images.githubusercontent.com/1158861/85106932-5c3c5c00-b20d-11ea-8cf6-ca6e82b244d7.png">
<img width="618" alt="Screenshot 2020-06-19 at 09 14 40" src="https://user-images.githubusercontent.com/1158861/85106925-59da0200-b20d-11ea-8227-aa0f3202edb5.png">
