### ISSUE TITLE
@JsonProperty

### ISSUE THREAD

**Issue by eriskooo** [kumuluz/kumuluzee#170]
Hello, why is @JsonProperty ignored ?

**Comment by MBJuric** [comment]
Can you be more specific and describe where is it ignored. Maybe a code snippet?

**Comment by eriskooo** [comment]
hello, in any DTO, where I would like to other name as field of property, does not work neither serializing / deserializing json

**Comment by cen1** [comment]
I tried to apply `@JsonProperty` to [one of our samples](https://github.com/kumuluz/kumuluzee-samples/tree/master/kumuluzee-rest) and it works as expected. Try to compare your setup.

**Comment by Jamsek-m** [comment]
@eriskooo Do you by any chance encounter this error when using rest-client?

**Comment by cen1** [comment]
Please reopen if the issue is not resolved.
