### ISSUE TITLE
DynamicFeature

### ISSUE THREAD

**Issue by eriskooo** [kumuluz/kumuluzee#173]
Hello is there any known issue using DynamicFeature ?

I can't inject application scoped bean into DynamicFeature provider

UnsatisfiedDependencyException: There was no object available for injection at SystemInjecteeImpl

Has kumuluz modified lifecycle ?

**Comment by cen1** [comment]
Hi. JAX-RS providers are not automatically recognised as part of the CDI context. If you want to inject a CDI bean into a provider try to annotate the provider with @ApplicationScoped.

**Comment by eriskooo** [comment]
thank you, seems to be change from JEE7 than. anyway, thank you, it's working !
