### ISSUE TITLE
Pluggable JPA Provider

### ISSUE THREAD

**Issue by n3k0** [kumuluz/kumuluzee#18]
Right now, KumuluzEE just works with EclipseLink, but it could be nice if it can works with other ORM like BatooJPA or another ORM (yes HIbernate may be).
Or, it is some way to do that?
Thanks in advance.

**Comment by MBJuric** [comment]
KumuluzEE now provides support for Hibernate (JPA 2.1). 
It is also possible to add other providers - possible contributions are welcome.
