### ISSUE TITLE
db pool config

### ISSUE THREAD

**Issue by eriskooo** [kumuluz/kumuluzee#181]
we are about to increase our db pool size, and I've found 2 options in doc -> which one is correct ?

 jdbc:postgresql,

 datasources:
      pool:
        max-size: 20

or

 datasources:
      max-pool-size: 20

thank you for clarification.

**Comment by urbim** [comment]
The first one. See: https://github.com/kumuluz/kumuluzee/wiki/EeConfig

**Comment by eriskooo** [comment]
thank you !
