### ISSUE TITLE
cassandra support

### ISSUE THREAD

**Issue by eriskooo** [kumuluz/kumuluzee#188]
Hello, I was unable to find any documentation for Cassandra support -> does Kumuluz have any issues with Cassandra ?

(or is there some smart in-memory DB able to be shared within multiple instances of service ?)

Many thanks,

e.

**Comment by urbim** [comment]
No, there are no known issues with KumuluzEE and Cassandra.

**Comment by eriskooo** [comment]
ok - is there any chance to find config examples in your github ?

**Comment by urbim** [comment]
We currently don't have any example, however you should be able to find and use generic Java examples for Cassandra on Google or your favourite search engine.

**Comment by eriskooo** [comment]
so no excpected problems, fine
