### ISSUE TITLE
OpenApi Swagger modifications

### ISSUE THREAD

**Issue by eriskooo** [kumuluz/kumuluzee#190]
Hello,

we are using https://github.com/kumuluz/kumuluzee-openapi -> is there any chance to for example modify openapi definition, that custom javascript will be added to rendered UI (I would love to send with every post request one extra header with random value)

Thank you,

e.

**Comment by urbim** [comment]
For modifying OAS, you can use [OASFilter](https://download.eclipse.org/microprofile/microprofile-open-api-1.1.2/microprofile-openapi-spec.html#_oasfilter). As for modifying UI itself, KumuluzEE uses [Swagger UI](https://github.com/swagger-api/swagger-ui), which is open-source. You can try modifying the code and hosting it yourself.

Also please use the respective extension repository when opening issues that only concern that extension. In this case it would be the repository you linked. This repository is meant for issues concerning the core KumuluzEE only.

**Comment by eriskooo** [comment]
thank you !
