### ISSUE TITLE
Config override using -D changed in 3.12?

### ISSUE THREAD

**Issue by danpfe** [kumuluz/kumuluzee#193]
Hi,

recently upgraded to 3.12 and wonder if I stumbled over a regression or if the change was intentional.

I have a embedded config.yaml on the classpath and sometimes I want to override a "default value" using -D, such as kumuluzee.server.http.port.

In 3.12, when the value is already present in config.yaml, the -Dkumuluzee.server.http.port=18080 has no effect, but did so in previous versions. However, if i remove the entry from the config.yaml then -D does work.

Thanks,
Daniel

**Comment by danpfe** [comment]
Previously used v3.10 and checked v3.11. It seems the "regression" is already present in 3.11. So works on 3.10, changed on 3.11.

**Comment by MBJuric** [comment]
Hi Daniel,
We will have a look at it shortly.
Thanks, Matjaz

**Comment by urbim** [comment]
This is definitely a regression. I will have the fix ready shortly. Thanks for reporting this.

**Comment by urbim** [comment]
Should be fixed in 3.12.1.
