### ISSUE TITLE
Roadmap and EE10 support?

### ISSUE THREAD

**Issue by kacert** [kumuluz/kumuluzee#222]
As there is no roadmap or any information on releases of kumuluzee any plans on EE10 support and microprofile 6? 

As the git has no commits in master for 1+ years?

I see there is java 21 branch there any ETA on that and release 5.0?

**Comment by MBJuric** [comment]
Hi. Yes, we are currently working on Java 21, Jakarta EE10 support and Microprofile 6. You can see some of the code here: https://github.com/kumuluz/kumuluzee/tree/feature/java-21
We plan to release a new version in February. 
In addition to this, we plan to release support for NATS messaging and Azure Functions.

**Comment by kacert** [comment]
Thanks.

**Comment by kacert** [comment]
so still no progress to a release?
