### ISSUE TITLE
KumuluzEE doesn't support SSL

### ISSUE THREAD

**Issue by raphaelLacerda** [kumuluz/kumuluzee#33]
Guys, 

i didn't find on the documentation how to configure the embedded jetty to run over HTTPS.

Is this a feature that is not possible yet using KumuluzEE?

For instance, to enable CORS, i had to add jetty-servlets dependency and enable it on web.xml configuration file.
https://www.eclipse.org/jetty/documentation/9.4.x/cross-origin-filter.html

**Comment by MBJuric** [comment]
Hi,
We provide HTTPS support in KumuluzEE Enterprise edition. However, we will soon provide support in Community edition as well. 
For microservices, having SSL support in microservice directly might not be best-practice, as it can make sense to offload SSL (for example: [here](https://www.nginx.com/blog/nginx-ssl/)).
Best regards,
Matjaz

**Comment by MBJuric** [comment]
Please have a look at: https://github.com/kumuluz/kumuluzee/wiki/TLS-SSL-support
