### ISSUE TITLE
Injection does not work for JAXWS endpoint

### ISSUE THREAD

**Issue by gpor89** [kumuluz/kumuluzee#55]
It looks like classes annotated with @Webservice are not managed by cdi container and therefore injections are not supported.

**Comment by MBJuric** [comment]
This is a known problem of JAX WS Metro RI, which we are using. They have an open issue here: https://github.com/javaee/metro-jax-ws/issues/935
Once they resolve this, we will include it in the KumuluzEE framework.
In our roadmap, we plan to include support for Apache CXF, however currently we do not have enough resources (however, possible contributions are welcome).

**Comment by gpor89** [comment]
Yes, i found that issue too. CXF would be a really must have, because instance without cdi support is hard to use. I'm looking forward to contribute.
