### ISSUE TITLE
ConfigBundle not working with no prefix (root properties)

### ISSUE THREAD

**Issue by TFaga** [kumuluz/kumuluzee#64]
When using the `@ConfigBundle` annotation to automatically populate bean properties from the config, if using the root prefix (i.e. not suppling a prefix) it's not picking them up. For instance:

```java
@ConfigBundle
@ApplicationScoped
public class ServiceProperties {

    private String authUrl;

    public String getAuthUrl() {
        return authUrl;
    }

    public void setAuthUrl(String authUrl) {
        this.authUrl = authUrl;
    }
}
```

and the `config.yml` file:

```yml
auth-url: http://localhost:9080/auth
```

The properties are not available in the bean as would be expected.

**Comment by jmezna** [comment]
fixed in https://github.com/kumuluz/kumuluzee/pull/66
