### ISSUE TITLE
Threads and CDI events

### ISSUE THREAD

**Issue by helander** [kumuluz/kumuluzee#69]
I need to run a thread as part of my application and this thread needs to be able to fire CDI events. What are my options when using Kumuluzee?

/Lars

**Comment by TFaga** [comment]
Hey. 

To clarify, you mean if you have a running thread outside the context of CDI, Servlets or the server in general and would like to fire a CDI event from there?

If so you can simply use the programatic way to retrieve the CDI `BeanManager` and then use it to fire the desired event. You can use this from everywhere in your code, you don't need a CDI or Servlet context present. Example:

```java
CDI.current().getBeanManager().fireEvent(ApiError.class, new AnnotationLiteral<CustomQualifier>() {});
```

The second parameter is only needed if you have a custom qualifier identifying your event. Be aware however, that any CDI beans that observe/consume the fired event can not be of scope `@RequestScoped` or `@SessionScoped`, as the event is fired out-of-bound from any request and as such a request or session is not present when consuming the event. Therefor the scope `@ApplicationScoped` an appropriate scope for a CDI bean consuming such events.

**Comment by helander** [comment]
Thank you very much for the feedback.
1) My observer is ApplicationScoped ( I realized that it had to be :) )
2) I want to fire from the context of another ApplicationsScoped bean, but how do I best create a thread in that context. Are you allowed to use unmanged threads or are there some way to create managed threads within my ApplicationScoped bean. I tried to use Runnable and ManagedExecutorService, but the MES seemed to be ignored (maybe I missed some dependency) ?

**Comment by helander** [comment]
Thank you very much, it got it to work :)

Actually I got it to work with a "normal" Thread as well, but I guess that
I could not rely on this being portable between different JEE servers, or
... ?


2017-10-30 16:00 GMT+01:00 Tilen Faganel <notifications@github.com>:

**Comment by TFaga** [comment]
Great!

Yes a normal Thread also works just fine. The example I gave brings it as close as possible to the `ManagedExecutorThread` API as possible. So while this is still not 100% portable, this changes are minimal. Change the `ExecutorThread` class to the `ManagedExecutorThread` class, remove the initialiser and shutdown and you're good to go. The rest of the code (your actual logic which schedules and executes threads) would remain the same.
