### ISSUE TITLE
Integration testing support?

### ISSUE THREAD

**Issue by high-stakes** [kumuluz/kumuluzee#76]
Hello,

I find kumuluz very promising but it is a very bad sign that there are no tests written for the framework.
Is there any plan to at least add examples of how to do integration testing with components enabled on-demand? Or any plans to write an arquillian adapter?

**Comment by urbim** [comment]
Hi!

The Arquillian adapter has been recently released under the [kumuluzee-testing](https://github.com/kumuluz/kumuluzee-testing) repository. Examples of integration testing can be found in [README](https://github.com/kumuluz/kumuluzee-testing/blob/master/kumuluzee-arquillian-container/README.md) and in [test repository of Arquillian Adapter project](https://github.com/kumuluz/kumuluzee-testing/tree/master/kumuluzee-arquillian-container/src/test/java/com/kumuluz/ee/testing/arquillian).

Hope this helps!
