### ISSUE TITLE
JAX-RS endpoints do not work if uber-jar is located in a directory named 'lib'

### ISSUE THREAD

**Issue by saulimus** [kumuluz/kumuluzee#80]
**Problem:**
If the generated uber jar is inside a directory called 'lib' JAX-RS endpoints do not work properly.

**Environment:**
Tried and reproduced in:
* Windows 10 cmd.exe (java version "1.8.0_144")
* Windows 10 Ubuntu Bash for Windows (openjdk version "1.8.0_151")
* Cloud Foundry Ubuntu 14.04.2 trusty (openjdk version "1.8.0_152")

**Background**
I found this out after trying to push my application to Cloud Foundry, for which I had to use a DistZip deployment archive.
(see https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-dist_zip.md)
In the DistZip archive, .jar files for the application reside in 'lib'.

**How to reproduce:**

You may need to replace ${project.build.finalName} with generated project name, in my case jax-rs-2.5.0-SNAPSHOT.
Run:
```
git clone https://github.com/kumuluz/kumuluzee-samples
cd kumuluzee-samples/jax-rs
mvn clean package
mkdir target/lib
cp target/${project.build.finalName}.jar target/lib
java -jar target/lib/${project.build.finalName}.jar
```
Then go to url: http://localhost:8080/v1/customers
Browser will return an error:
```
HTTP ERROR 404
Problem accessing /v1/customers. Reason:
    Not Found
```

**Comment by TFaga** [comment]
Fixed in #81
