### ISSUE TITLE
Uberjar with beans.xml does not run in directory containing spaces

### ISSUE THREAD

**Issue by saulimus** [kumuluz/kumuluzee#86]
**Problem:**
Application does not run

**Environment:**
* Windows 10
  Fails with both cmd.exe and Bash on Ubuntu for Windows
* KumuluzEE 2.5.1

**How to reproduce:**
1. Project must have beans.xml file in META-INF\beans.xml
2. Generate uberjar and move it to a directory that includes spaces. 
3. Run jar.

Attachments:
[20180108_beansxml_error_log.txt](https://github.com/kumuluz/kumuluzee/files/1611497/20180108_beansxml_error_log.txt)
[beans.xml.txt](https://github.com/kumuluz/kumuluzee/files/1611495/beans.xml.txt)

**Comment by MBJuric** [comment]
We will look at the issue and come back shortly.

**Comment by TFaga** [comment]
Merged in #92
