### ISSUE TITLE
Running uberjar fails infrequently

### ISSUE THREAD

**Issue by saulimus** [kumuluz/kumuluzee#87]
**Problem**:
Infrequently (not always) the boot loader fails to initialize application properly.
This seems to be dependant on the load order of .jars included in the uber jar.
I have managed to reproduce this with the JAX-RS sample where approx 1/20 times the uberjar fails to run.
With my own project it fails a lot more frequently.

**Environment:**
* Windows 10
  Tested with both cmd.exe and Bash on Ubuntu on Windows

**Tested with:**
* Latest JAX-RS sample (a8dae042893f3f69932537346dd5eae8d4611c76)
* Own JAX-RS project w/ kumuluzee 2.5.1 (not open source)

**How to reproduce:**
* Checkout JAX-RS sample (https://github.com/kumuluz/kumuluzee-samples/tree/master/jax-rs)
* Run: mvn clean package
* Run about 20-30 times: java -Dcom.kumuluz.ee.loader.debug=true -jar target/jax-rs-2.5.0-SNAPSHOT.jar

**Attachments:**
For these the system variable com.kumuluz.ee.loader.debug was set to true.

* JAX-RS:
[jaxrs-fail1.txt](https://github.com/kumuluz/kumuluzee/files/1611699/jaxrs-fail1.txt)
[jaxrs-fail2.txt](https://github.com/kumuluz/kumuluzee/files/1611700/jaxrs-fail2.txt)
[jaxrs-success.txt](https://github.com/kumuluz/kumuluzee/files/1611703/jaxrs-success.txt)

* Own app:
[ownapp-fail1.txt](https://github.com/kumuluz/kumuluzee/files/1611704/ownapp-fail1.txt)
[ownapp-fail2.txt](https://github.com/kumuluz/kumuluzee/files/1611706/ownapp-fail2.txt)
[ownapp-success.txt](https://github.com/kumuluz/kumuluzee/files/1611708/ownapp-success.txt)

**Comment by MBJuric** [comment]
We are already working on this issue and will let you know. In the mean time, please use the exploded format.

**Comment by TFaga** [comment]
Merged in #92
