### ISSUE TITLE
maven build fails

### ISSUE THREAD

**Issue by surajchhetry** [kumuluz/kumuluzee#88]
Hi,
I am getting following error when using version 2.5.1

 Failed to collect dependencies at com.kumuluz.ee:kumuluzee-microProfile-1.2:jar:2.5.1 -> com.kumuluz.ee.config:kumuluzee-config-mp:jar:1.1.0: Failed to read artifact descriptor for com.kumuluz.ee.config:kumuluzee-config-mp:jar:1.1.0: Could not find artifact com.kumuluz.ee:kumuluzee-bom:pom:2.5.0-SNAPSHOT -> [Help 1]

**Comment by TFaga** [comment]
Hey,

Thanks for the heads up. There was indeed an issue with versions of the dependencies when packaging the release of the [`kumuluzee-config-mp`](https://github.com/kumuluz/kumuluzee-config-mp) extension.

We've already corrected the issue there and released a quick update [`1.1.1`](https://github.com/kumuluz/kumuluzee-config-mp/releases/tag/v1.1.1) to address this. A fix in the main `kumuluzee` project will follow shortly.

In the meantime you can add the main OSSHR Sonatype repository to your projects:

```xml
<repository>
    <id>sonatype-snapshots</id>
    <name>Sonatype Snapshots</name>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
        <enabled>false</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>
```

As mentioned in the release of `kumuluzee-config-mp`, this is only used to resolve certain `pom.xml` files and will not bring in any snapshot dependencies even if added.

The issue will be resolved shortly with a quick fix to KumuluzEE.

**Comment by surajchhetry** [comment]
Thanks for your support.

**Comment by surajchhetry** [comment]
Thanks after adding mentioned repository it worked fine.
