### ISSUE TITLE
When returning JsonObject from JAX-RS 

### ISSUE THREAD

**Issue by surajchhetry** [kumuluz/kumuluzee#91]
Hi,
When we returning JsonObject from JAX-RS , we get following json message in kumuluz. Where if I run same code in other micro profile like wildfly-swarm or payara, I got different json output. So my question is how can I got same response with kumuluz using JsonObject ???

```java
 @GET
  public Response ping() {
      JsonObject jsonObject = Json.createObjectBuilder()
                .add("message", "Hello Java Microprofile.")
                .build();
        return Response.ok(jsonObject).build();
    }
```
Kumuluz output
```json
{
  "message": {
    "valueType": "STRING",
    "string": "Hello Java Microprofile.",
    "chars": "Hello Java Microprofile."
  }
}
```
wildfly-swarm

```json
{
  "message": "Hello Java Microprofile."
}
```

**Comment by surajchhetry** [comment]
When I changed return type to string , it is working as expected.
```java
 @GET
    public Response ping() {
        JsonObject jsonObject = Json.createObjectBuilder()
                .add("message", "Hello Java Microprofile.")
                .build();
        return Response.ok(jsonObject.toString()).build();
    }
```

**Comment by TFaga** [comment]
Currently only Jackson is used for (de)serialisation of Objects into JSON, which treats the `JsonObject` as any other object and serialises its properties. 

We're planning on adding both JSON-P and JSON-B support. In the meantime your solution works the best.
